// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernRecrut.Postulation.API.Data;

#nullable disable

namespace ModernRecrut.Postulation.API.Migrations
{
    [DbContext(typeof(PostulationsContext))]
    [Migration("20231211010040_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("ModernRecrut.Postulation.API.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomEmeteur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteDetail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PostulationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostulationId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("ModernRecrut.Postulation.API.Models.Postulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CandidatId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDisponibilite")
                        .HasColumnType("TEXT");

                    b.Property<int>("OffreDEmploiId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PretentionSalariale")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Postulation");
                });

            modelBuilder.Entity("ModernRecrut.Postulation.API.Models.Note", b =>
                {
                    b.HasOne("ModernRecrut.Postulation.API.Models.Postulation", "Postulation")
                        .WithMany("Notes")
                        .HasForeignKey("PostulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postulation");
                });

            modelBuilder.Entity("ModernRecrut.Postulation.API.Models.Postulation", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
